### ISSUE TITLE
Trying to reference an undefined object

### ISSUE THREAD

**Issue by bryanj4** [jeffbernst/creative-crypto#27]
In `src/actions/index.js` on line 124-130 you assign urls to images. However some posts do not have these images and you will end up referencing a null identifier and it will cause all sorts of havoc. I suggest putting try-catch statements around the assignment operators and give a stock no-image is here image. If you try running a local dev copy with the steem username `tribesteemup` then the error will occur.

~~~  
let image
  if (isDlive)
    image = jsonMetadata.thumbnail
  else if (isBusy)
    **image = bodyHtml.match(/<img.*?src=['"](.*?)['"]/)[1]**
  else
    image = jsonMetadata.image[0]
~~~

**Comment by bryanj4** [comment]
Problem I keep on finding is that for my dtube posts there aren't any images in the parsed data. Whether the jsonMetadata or the bodyHtml variables. I feel like none of your posts are dTube posts so you won't experience the problems that I am.

**Comment by jeffbernst** [comment]
Hmm, do you have the most recent version of the code? I actually added logic to handle posts for DTube and DLive because we have a bunch of posts from each on the site. There's a styling problem in master that I'm fixing right now, but if you grab the updated actions index then it should handle everything.

Thanks for your advice though! This was my first React project so I'm happy to have other people looking through the code. 👍

**Comment by bryanj4** [comment]
I'm still having an issue. I just started working on this today. Try using my username `tribesteemup` and you'll get the same issue as me.

~~~error message:  TypeError: Cannot read property '1' of null
    at formatPostData (index.js:125)
    at index.js:168
    at Array.map (<anonymous>)
    at Object._callee2$ (index.js:167)
    at tryCatch (runtime.js:62)
    at Generator.invoke [as _invoke] (runtime.js:296)
    at Generator.prototype.(:3000/anonymous function) [as next] (http://localhost:3000/static/js/bundle.js:112117:21)
    at step (index.js:87)
    at index.js:87
post-feed.js:21 TypeError: Cannot read property '1' of null
~~~
This is caused by loading the second post on the profile.

**Comment by jeffbernst** [comment]
That's weird, I could've sworn I had it working before. Can't work on it tonight but I'll try to figure out the bug on Monday or Tuesday.

**Comment by bryanj4** [comment]
I worked on it enough today and will give myself a break tomorrow. Contact me if you want to work through it together.

Sincerely,

Jake Bryan
Keybase
Cell: +1 2565290690

-------- Original Message --------

**Comment by bryanj4** [comment]
Any update @jeffbernst?

**Comment by jeffbernst** [comment]
Hey sorry! Got very side tracked on my other project.

Did you get everything sorted out? I'm looking through your closed pull request and stuff. I can work on this stuff now.

**Comment by bryanj4** [comment]
Accidentally tried to do a PR to your project when I meant to do it for another repository. TribeSteemUp has forked your website to show off our curated authors.

Sincerely,

Jake Bryan
[Keybase](https://keybase.com/bryanj4)
Cell: [+1 2565290690](http://tel)

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by jeffbernst** [comment]
Yeah I saw the post, glad to see someone else is using our code!

Did you figure out the bug you had before? I just loaded up the original site with @tribesteemup and see the error.

**Comment by jeffbernst** [comment]
I saw the post -- glad to see someone else is using our code!

I'll take a crack at fixing the bug now.

**Comment by jeffbernst** [comment]
You might have seen this, but the `getPost` function in the actions index is going to have to be updated to account for direct linking to posts that have been resteemed.

Right now @creativecrypto isn't using any resteems, so when you go directly to a post (i.e. thecreativecrypto.com/permlink-here) it gets the post with `getPost` and automatically uses @creativecrypto as the account name. For resteemed posts it will time out because it won't be able to find a post for @tribesteemup with that permlink.

**Comment by bryanj4** [comment]
Oh okay. I need to add to the reducer the post's username in order to get the resteem function to work and show up properly?

**Comment by bryanj4** [comment]
For best practice, I separate all of the actions, reducers, etc. to see it more clearly. I understand what is happening now. This has been a great project to get back to reading and understanding React.js

**Comment by jeffbernst** [comment]
> Oh okay. I need to add to the reducer the post's username in order to get the resteem function to work and show up properly?

Yeah exactly!

> For best practice, I separate all of the actions, reducers, etc. to see it more clearly. I understand what is happening now. This has been a great project to get back to reading and understanding React.js

Ah okay, yeah I'm still getting a handle on best practices.

I just figured out the DTube bug and got it working. Just need to clean it up and I'll make a pull request and send it to you.

Basically the image was coming in as part of the body, then `Body.js` was stripping it out (as you mentioned). Side note: everything in that folder is from the Busy.org code base. So all it takes is commenting out the line that strips out the image in `Body.js` and then using the same regex I used Busy posts to grab the image url before parsing.

I feel like this might have something to do with the posts getting resteemed in Busy, which might change the format of the data that comes through.

**Comment by bryanj4** [comment]
No worries Jeff. You're doing a great job and I really appreciate your work and your project. The tribesteemup community will be giving you a big upvote for your efforts.

**Comment by jeffbernst** [comment]
Awesome, thanks! Glad you guys are finding it useful :D

Also, just realized that the infinite scroll component for the post feed isn't set up to load more posts after the initial 50 that are loaded for the main API call. So that will have to be set up with a new type of API call to load more posts.

[Here](https://github.com/jeffbernst/creative-crypto/pull/30)'s the pull request I just merged with the update.

Good luck getting the tribesteemup version up and running! Let me know if you run into any other problems 👍
